/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.graphic.wine;

import ClassMetier.Bouteille;
import ClassMetier.Cepage;
import ClassMetier.Couleur;
import ClassMetier.Vin;
import static java.lang.Integer.toString;
import java.util.ArrayList;
import java.util.ArrayList;
import java.util.Vector;
import javax.management.StringValueExp;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 82103
 */
public class frmPrincipal extends javax.swing.JFrame {

    ArrayList<Bouteille> mesBouteilles = new ArrayList();
    Vector v;
    DefaultTableModel dtmBouteilles;
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBout = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMill = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCepage = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPrix = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtCouleur = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtValeur = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtPercentBlanc = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtPercentRouge = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtPercentRose = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jScrollPane5.setViewportView(jTextPane4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Broadway", 0, 24)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setText("Project Vin");

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        jLabel2.setText("Liste des bouteuille");

        tblBout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Vin", "Quantité"
            }
        ));
        tblBout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoutMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBout);

        jLabel3.setText("Millésime");

        jLabel4.setText("Prix");

        jLabel5.setText("Cépage");

        jLabel6.setText("couleur");

        jScrollPane2.setViewportView(txtMill);

        jScrollPane3.setViewportView(txtCepage);

        jScrollPane4.setViewportView(txtPrix);

        jScrollPane6.setViewportView(txtCouleur);

        jLabel7.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel7.setText("Valeur de la cave");

        txtValeur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        jScrollPane7.setViewportView(txtValeur);

        jScrollPane8.setViewportView(txtPercentBlanc);

        jScrollPane9.setViewportView(txtPercentRouge);

        jScrollPane10.setViewportView(txtPercentRose);

        jLabel8.setText("Rouge");

        jLabel9.setText("Blanc");

        jLabel10.setText("Rosé");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dtmBouteilles = (DefaultTableModel)tblBout.getModel();
        Couleur blanc = new Couleur("Blanc");
        Couleur rose = new Couleur("Rosé");
        Couleur rouge = new Couleur("Rouge");

        // Les cépages du vin
        Cepage beaujolais = new Cepage("Beaujolais");
        Cepage chardonnay = new Cepage("Chardonnay");
        Cepage gamay = new Cepage("Gamay");
        Cepage pinotNoir = new Cepage("Pinot noir");
        Cepage sauvignon = new Cepage("Sauvignon");

        // Les vins
        Vin vin1 = new Vin("Juliénas", 2005, beaujolais, rouge,13.78);
        Vin vin2 = new Vin("Saint Amour", 2012, beaujolais, blanc,18);
        Vin vin3 = new Vin("Brouilly", 2018, beaujolais, rouge,14.5);
        Vin vin4 = new Vin("Morgon", 2015, beaujolais, rose,21.34);
        Vin vin5 = new Vin("Bourgogne Côte de Beaune", 2002, chardonnay, blanc,39.5);
        Vin vin6 = new Vin("Aligoté", 2016, chardonnay, blanc,7.12);
        Vin vin7 = new Vin("Bourgogne Côte de Nuits", 2000, chardonnay, rose,11.67);
        Vin vin8 = new Vin("Chablis", 2011, chardonnay, blanc,15.17);
        Vin vin9 = new Vin("Champagne", 2014, chardonnay, blanc,24.71);
        Vin vin10 = new Vin("La Roche", 2005, gamay, rouge,12.45);
        Vin vin11 = new Vin("Le Carquelin", 2005, gamay, rouge,15.98);
        Vin vin12 = new Vin("Morgon Vieilles Vignes", 2005, gamay, rouge,19.54);
        Vin vin13 = new Vin("Coeurs de terroirs", 2005, gamay, rose,9.80);
        Vin vin14 = new Vin("Alox Corton", 2005, pinotNoir, rouge,17.65);
        Vin vin15 = new Vin("Edelzwicker ", 2017, pinotNoir, blanc,23.81);
        Vin vin16 = new Vin("Romanée Conti", 2009, pinotNoir, rouge,14.83);
        Vin vin17 = new Vin("Château d'Yguem", 2010, sauvignon, rose,11.56);
        Vin vin18 = new Vin("Château Guiraud", 2003, sauvignon, rouge,16.90);
        Vin vin19 = new Vin("Château Coutet", 2017, sauvignon, rouge,22.74);
        Vin vin20 = new Vin("Château Suduiraut", 2007, sauvignon, rouge, 8.63);

        // Les bouteilles
        Bouteille b1 = new Bouteille(1, 125, vin1);
        Bouteille b2 = new Bouteille(2, 56, vin2);
        Bouteille b3 = new Bouteille(3,23, vin3);
        Bouteille b4 = new Bouteille(4, 14, vin4);
        Bouteille b5 = new Bouteille(5, 87, vin5);
        Bouteille b6 = new Bouteille(6, 34, vin6);
        Bouteille b7 = new Bouteille(7, 78, vin7);
        Bouteille b8 = new Bouteille(8, 19, vin8);
        Bouteille b9 = new Bouteille(9, 41, vin9);
        Bouteille b10 = new Bouteille(10, 12, vin10);
        Bouteille b11 = new Bouteille(11, 25, vin11);
        Bouteille b12 = new Bouteille(12, 46, vin12);
        Bouteille b13 = new Bouteille(13, 62, vin13);
        Bouteille b14 = new Bouteille(14, 5, vin14);
        Bouteille b15 = new Bouteille(15, 44, vin15);
        Bouteille b16 = new Bouteille(16, 62, vin16);
        Bouteille b17 = new Bouteille(17, 21, vin17);
        Bouteille b18 = new Bouteille(18, 71, vin18);
        Bouteille b19 = new Bouteille(19, 37, vin19);
        Bouteille b20 = new Bouteille(20, 92, vin20);
        
        
        mesBouteilles.add(b1);mesBouteilles.add(b2);mesBouteilles.add(b3);
        mesBouteilles.add(b4);mesBouteilles.add(b5);mesBouteilles.add(b6);
        mesBouteilles.add(b7);mesBouteilles.add(b8);mesBouteilles.add(b9);
        mesBouteilles.add(b10);mesBouteilles.add(b11);mesBouteilles.add(b12);
        mesBouteilles.add(b13);mesBouteilles.add(b14);mesBouteilles.add(b15);
        mesBouteilles.add(b16);mesBouteilles.add(b17);mesBouteilles.add(b18);
        mesBouteilles.add(b19);mesBouteilles.add(b20);
        
        double valeur = 0 ;
        int numberOfRed = 0;
        int numberOfWhite = 0;
        int numberOfRose = 0;
        
        for(Bouteille bou : mesBouteilles){
            v = new Vector();
            v.add(bou.getIdBouteille());
            v.add(bou.getLeVin().getNomVin());
            v.add(bou.getQuantiteBouteille());
            dtmBouteilles.addRow(v);
            valeur = valeur + (bou.getQuantiteBouteille()*bou.getLeVin().getPrixDuVin());
             
            if(("Rouge").equals(bou.getLeVin().getLaCouleur().getNomCouleur())){
                numberOfRed++;
            }
            if(bou.getLeVin().getLaCouleur().getNomCouleur().compareTo("Blanc")==0){
                numberOfWhite++;
            }
            if(("Rosé").equals(bou.getLeVin().getLaCouleur().getNomCouleur())){
                numberOfRose++;
                
            }
        }
        
        System.out.println(numberOfRed);
        System.out.println(mesBouteilles.size());
        int totalBouteuille = numberOfRed + numberOfRose + numberOfWhite; 
        txtValeur.setText(String.valueOf(valeur)+ "euros");
        txtPercentRouge.setText(String.valueOf(((double)numberOfRed/mesBouteilles.size())*100)+"%");
        txtPercentBlanc.setText(String.valueOf(((double)numberOfWhite/mesBouteilles.size())*100)+"%");
        txtPercentRose.setText(String.valueOf(((double)numberOfRose/mesBouteilles.size())*100)+"%");
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tblBoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoutMouseClicked
        int selectedBou;
        // txt 다 비우기 
        selectedBou =Integer.parseInt(tblBout.getValueAt(tblBout.getSelectedRow(), 0).toString());
        for(Bouteille bou : mesBouteilles){
            if(selectedBou == bou.getIdBouteille()){
                txtMill.setText(String.valueOf(bou.getLeVin().getMillesimeVin())); 
                txtPrix.setText(String.valueOf(bou.getLeVin().getPrixDuVin()));
                txtCepage.setText(String.valueOf(bou.getLeVin().getLeCepage().getNomCepage()));
                txtCouleur.setText(String.valueOf(bou.getLeVin().getLaCouleur().getNomCouleur()));
            }
        }
    }//GEN-LAST:event_tblBoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTable tblBout;
    private javax.swing.JTextPane txtCepage;
    private javax.swing.JTextPane txtCouleur;
    private javax.swing.JTextPane txtMill;
    private javax.swing.JTextPane txtPercentBlanc;
    private javax.swing.JTextPane txtPercentRose;
    private javax.swing.JTextPane txtPercentRouge;
    private javax.swing.JTextPane txtPrix;
    private javax.swing.JTextPane txtValeur;
    // End of variables declaration//GEN-END:variables
}
